# Performance Measurements of logistic Regression

In [3]:
import pandas as p                #importing the necessary modules and libraries
import matplotlib.pyplot as plt
import seaborn as s
import numpy as n

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [5]:
df=p.read_excel("Data1.xlsx")   #classified data according to cities and average, max and min values of NO2 in them


In [6]:
from sklearn.preprocessing import LabelEncoder  #converting into numeric form so it is machiene readable

In [7]:
# Adding a new column according to the data.
AQI=['Satisfactory','Good' , 'Good','Satisfactory','Good', 'Good', 'Good','Satisfactory','Satisfactory', 'Good', 'Moderate', 'Good', 'Good','Good','Satisfactory','Good', 'Good', 'Moderate','Good','Satisfactory','Good','Good','Satisfactory','Good','Moderate',]

In [8]:
df['AQI']=AQI #added to data frame

In [9]:
df.head()

City  Last Update   Avg1   Max1  Min1           AQI
0  Ahmedabad            0  42.08  39.00  7.80  Satisfactory
1     Aizwal            0   4.10   5.20  3.10          Good
2  Amaravati            0  10.36  16.70  6.53          Good
3   Amritsar            0  51.27  28.02  7.79  Satisfactory
4  Bengaluru            0  31.04  19.65  9.72          Good

In [10]:
# Adding class to the dataset which is derieved on the values according to AQI
df['class'] = df.AQI.map({'Good':3, 'Satisfactory':2,'Moderate':1,}) #class defined 

In [11]:
del df['AQI']

In [12]:
df.head()  

City  Last Update   Avg1   Max1  Min1  class
0  Ahmedabad            0  42.08  39.00  7.80      2
1     Aizwal            0   4.10   5.20  3.10      3
2  Amaravati            0  10.36  16.70  6.53      3
3   Amritsar            0  51.27  28.02  7.79      2
4  Bengaluru            0  31.04  19.65  9.72      3

In [13]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['City','Last Update','Avg1','Max1','Min1','class']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i].astype(str))

In [14]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [15]:
X= df.drop(labels='class',axis=1)
y=df.loc[:,'class']

In [16]:
#spliting our data to training sets and test sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.2, random_state=1,stratify=y)

In [17]:
len(X_train)  #no of values used for training 

20

In [18]:
len(X_test)   #no of values used for testing

5

In [19]:
X_test #values we are going to test on which are random

City  Last Update  Avg1  Max1  Min1
17    17            0     8    24    15
14    14            0    19    11     5
2      2            0     1     1    17
1      1            0    15    19    10
23    23            0     6     0    12

In [20]:
X_train        #samples used to train our model

City  Last Update  Avg1  Max1  Min1
7      7            0    24    22     9
19    19            0     4    23    14
8      8            0    22    13    23
20    20            0    13    15    18
15    15            0    11     6     3
9      9            0    18    16    13
5      5            0     2     4    16
6      6            0    16    14     1
13    13            0    23     2    11
12    12            0     7     7    22
21    21            0    12    10     8
4      4            0    14     3    24
3      3            0    20     8    19
10    10            0     5    20     4
0      0            0    17    18    20
24    24            0     9    21     7
18    18            0    10     9    21
22    22            0    21    17     6
11    11            0     0     5     0
16    16            0     3    12     2

In [25]:
from sklearn.model_selection import cross_val_score  #Performing logistic regression and cross validation
from sklearn.linear_model import LogisticRegression

In [26]:
logR= LogisticRegression()  #object of a class

logR.fit(X_train,y_train)   #training for our model using fit method

predictR = logR.predict(X_test)  #ready to make predictions by calling predict method

print("")
print("Classification report of Logistic Regression Results:")
print("")

print(classification_report(y_test,predictR)) # shows classification metrics precision, recall and f1 score

# Accuracy is the correctly classified data instances over the total number of data instances.
# Cross validation is to evaluate our models
accuracy = cross_val_score(logR ,X, y, cv=7) #splitting the data according to cv dividing it into training and testing
print("Cross validation test results of accuracy:")
print(accuracy)
print("")
# get mean of every field
print("Accuracy result of Logistic Regression is:",accuracy.mean()*100)
print("")

cm1=confusion_matrix(y_test,predictR) #evaluating the performance of a classification model
print("Confusion Matrix result of Logistic Regression is:\n",cm1)
print("")
sensitivity1= cm1[0,0]/(cm1[0,0]+cm1[0,1])
print("Senstivity :",sensitivity1) #  Cases actual positive cases that got predicted as true
print("")
specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print("specificity :",specificity1)  #  Cases actual positive cases that got predicted as false
print("")


Classification report of Logistic Regression Results:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         1
           2       0.67      0.67      0.67         3

    accuracy                           0.40         5
   macro avg       0.22      0.22      0.22         5
weighted avg       0.40      0.40      0.40         5

Cross validation test results of accuracy:
[0.75       0.5        0.5        1.         0.66666667 0.66666667
 1.        ]

Accuracy result of Logistic Regression is: 72.61904761904762

Confusion Matrix result of Logistic Regression is:
 [[0 1 0]
 [0 0 1]
 [0 1 2]]

Senstivity : 0.0

specificity : nan



In [23]:
TN = cm1[0][0]
FN = cm1[1][0]
TP = cm1[1][1]
FP = cm1[0][1]
print("True positive :",TP)
print("True negative :",TN)
print("False positive :",FP)
print("False negative :",FN)
print("")
TPR = TP/(TP+FN)
TNR = TN/(TN+FP)
FPR = FP/(FP+TN)
FNR = FN/(TP+FN)
print("")
print("True positive Rate :",TPR)
print("True negative Rate :",TNR)
print("False positive Rate:",FPR)
print("False negative Rate :",FNR)

True positive : 0
True negative : 0
False positive : 1
False negative : 0


True positive Rate : nan
True negative Rate : 0.0
False positive Rate: 1.0
False negative Rate : nan
